  title: stackgres
  description: "Install Stackgres on OCI Kubernetes"
  stackDescription: "Install Stackgres on OCI Kubernetes"
  schemaVersion: 1.0.0
  version: "20250320"
  locale: "en"

  variableGroups:
  - title: Kubernetes Configuration
    visible: true
    variables:
    - kubernetes_compartment_ocid
    - kubernetes_cluster_ocid

  - title: Stackgres
    visible: true
    variables:
    - stackgres_chart_version

  variables:
      
    kubernetes_compartment_ocid:
      type: oci:identity:compartment:id
      description: "The compartment where the OKE cluster is located."
      required: true
      title: OKE cluster compartment
      default: ${compartment_ocid}
      
    kubernetes_cluster_ocid:
      title: OKE cluster
      description: "The OKE cluster to deploy the bootstrap apps."
      type: oci:container:cluster:id
      dependsOn:
        compartmentId: ${kubernetes_compartment_ocid}
      required: true

    stackgres_chart_version:
      type: string
      title: "Stackgres Chart Version"
      description: "The version of the Stackgres chart to install."
      required: true
      visible: true

    tenancy_ocid:
      type: oci:identity:tenancy:id
      description: The Oracle Cloud Infrastructure tenancy OCID.
      required: true
      visible: false

    region:
      type: string
      description: The Oracle Cloud Infrastructure region.
      required: true
      visible: false

    oci_profile:
      type: string
      description: The Oracle Cloud Infrastructure CLI profile.
      required: true
      visible: false
      default: "DEFAULT"